spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/haebang01;MODE=MYSQL
    username: test
    password: test
    driver-class-name: org.h2.Driver
  profiles:
    active: local

  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  project.user.UserClient: DEBUG

cors:
  originPatterns: http://localhost:8081

feign:
  url:
    scrape: 192.168.200.101:3000/scrape
